#:schema node_modules/wrangler/config-schema.json
name = "valley"
compatibility_flags = [ "experimental:nodejs_compat_v2" ]
compatibility_date = "2024-09-23"
pages_build_output_dir = "./build/client"
