#:schema node_modules/wrangler/config-schema.json
name = "valley"
compatibility_date = "2024-09-26"
# main = "./server.ts"
# workers_dev = true

compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "./build/client"

# https://developers.cloudflare.com/workers/static-assets/binding/
# [assets]
# directory = "./build/client"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
[observability]
enabled = true

# [build]
# command = "yarn build"
