#:schema node_modules/wrangler/config-schema.json
name = "valley"
type = "javascript"
workers_dev = true

[site]
bucket = "./public"
entry-point = "."

[build]
command = "yarn build"
watch_dir = "app"

[build.upload]
format = "service-worker"
