FROM node:20-alpine

RUN apk update && apk add --no-cache openssl

RUN yarn add sharp --ignore-engines

WORKDIR /app

CMD yarn workspace @valley/db db:push ; VIPS_CONCURRENCY=$(nproc) yarn turbo dev -F api
